import { Events } from 'discord.js';

const MESSAGE_CHANCE = 25; // Chance (percentage) of replying to a message
const MESSAGE_DELAY = 1; // Delay (in seconds) before replying
const MESSAGE_IMAGE = 'https://static.wikia.nocookie.net/aceattorney/images/4/4e/Ernest_Placating_1.gif'; // Image to send with the message

const AMANO_QUOTES = [
	"Oh! Miles, my boy! I'm sorry to involve you in such an affair just after you've returned.",
	'No, no, no. Think nothing of it. As you know, Manfred and I go way back. I consider a beloved disciple of his to be like one of my own blood.',
	"If you ever want to go overseas again, you need only to ask. I can use my company's vast network to send you anywhere at any time.",
	'Now then, have you found Lance yet, Miles? Please... I miss my poor boy dearly!',
	'Wh-- Hold on there! Then, what happened to all that money!?',
	'Whaaaaat!?',
	'Oh. It was yesterday... A call came to the house. From the receiver came the sound of my son... "Help me, Daddy!"... *sniff*',
	'You don\'t understand. He hasn\'t called me "Daddy" in ages... It was incredibly moving... I wish I had recorded him saying that.',
	'How will telling you about Lance help you get him back?',
	"Very well, then. Lance is my one and only son, and he turned 21 this year. He is very much like me when I was his age -- kind and very attractive. I'm sure women simply can't keep their hands off of him.",
	"Now that you mention it, I haven't been able to get in contact with our butler, Oliver.",
	"Yes, his name is Oliver Deacon. He's been with our family for years now. He gets along so well with Lance, so I thought maybe he would know where my son is...",
	"As a butler, he's outstanding. He even serves as Lance's personal private tutor. He took a brief leave recently, but even after it was over, I haven't been able to reach him.",
	"They said they hadn't seen him. I've tried everything I could think of, Miles. ...Do you think this could have something to do with Lance's kidnapping?",
	'Ah... Seeing that badge reminds me of Manfred. Now, HE was one fine prosecutor, the best of the best.',
	"Hmm... I sense that you don't really want to talk about him.",
	"Your hard countenance... I don't know what you're thinking or feeling... ...but mark my words, I think you are Manfred's true successor. I really do.",
	'Ho, ho! That looks to be something with quite a bit of value. But then, all things have some value attached to them. Only by probing deep into the unknown can we become true winners in this world, Miles.',
	"Oh! I've never seen you so passionate before, Miles. Good luck to you, my boy.",
	"Just what sort of operation is this, that they would allow their valuables to be stolen!? It's a disgrace to the way businesses are run everywhere!",
	"Stealing is an abominable behavior, don't you agree, little miss!?",
	"I-It's Oliver!",
	"Yes... He's my butler... How could something like this have happened!?",
	"Yes... That's my butler, Oliver... How could something like this have happened!?",
	"Miles, my boy, I can't thank you enough.",
	"I'm still in shock over what happened to Oliver... ...but I have to say I'm relieved that Lance is alright. Oh, that's right! I mustn't forget to pass this on to Lance as soon as the police are finished with him.",
	"Ah, the way Lance is being chased after by women reminds me of someone I know. I almost can't believe he received yet another love letter, you know. Here! Take a look for yourself.",
	'Ah... Seeing that badge reminds me of Manfred. Now, HE was one fine prosecutor, the best of the best.',
	"Hmm... I sense that you don't really want to talk about him.",
	"Your hard countenance... I don't know what you're thinking or feeling... ...but mark my words, I think you are Manfred's true successor. I really do.",
	"Just what sort of operation is this, that they would allow their valuables to be stolen!? It's a disgrace to the way businesses are run everywhere!",
	"Stealing is an abominable behavior, don't you agree, little miss!?",
	"Oliver... *sigh* He served me well for such a long time. What am I going to do without him...? I'm afraid my money will continue to be dampened by my tears in the long nights ahead.",
	'Oliver...',
	'Oh...Coden Livorea? ...Veldor Dalein...?',
	'Ho, ho! That looks to be something with quite a bit of value. But then, all things have some value attached to them. Only by probing deep into the unknown can we become true winners in this world, Miles.',
	'Please, wait.',
	"Ho ho ho. Miles, my boy. It looks like you're really giving it your all. And Lance... It's not good to cause trouble for others.",
	"Let's see... You are the one in charge of the investigation, correct?",
	"I'm sorry that my son has been nothing but trouble. This probably won't make up for anything, but I have some evidence for you.",
	"I couldn't wait around for the police, so I went and found these myself. It appears that they were disposed of in the sea.",
	'There, there, now. Agent Lang, please calm down.',
	'Ho ho ho. There, there, now. There is no need to be so upset.',
	"Now, now, now. This wasn't meant to strong-arm you into anything. It's just a request. I'm only asking that you please respect the laws of the land.",
	"I've already got the results back. I had a special forensics research lab that I'm on good terms with conduct the tests. They verified that the blood on this costume belonged to Oliver. As for the gun... ..the only fingerprints they could find were yours, Lauren!",
	"You disappoint me, Miles. I can't believe that you... that you would... cause my son such stress and heartache! Thank goodness I was able to find the final pieces of evidence. With this, you'll have no reason left to push my poor boy around!",
	"Well? Are these not the most definitive pieces of evidence you've ever seen?",
	"There's no mistake about it. Through my connections, I had the best forensics techniques money can buy performed.",
	'What? Are you trying to pick an argument with me!?',
	'Which piece is that?',
	'Ho ho ho. Right you are. Even if it cost me millions, I would have had the killer found.',
	"But there's been no mistake! We found fingerprints!",
	'Grrrrrr...',
	'Miles, my boy. Say no more!',
	'Yes, please, do something! Stop that boy from speaking any more nonsense!',
	'H-How dare you!?',
	"Now, now, let's hold on for a second. There is no need to obtain approval.",
	'Agent Lang. If you would please take a look at this.',
	'Ho ho ho. As you can see, I am now the legal owner of the haunted house.',
	'I ran into the owner of the park earlier, and we made the deal almost immediately. How quickly things move when you can prepare a million dollars in the blink of an eye.',
	"Oh, that's right. This disgusting suitcase belongs to you, doesn't it? I don't have any more use for it, so you may have it back now.",
	"My Lance is a good boy. He even apologized for the kidnapping a bit earlier... ...so I do believe that I will forgive him. After all, he did return the ransom money. That's the way things are, so if you would please discuss things with me from now on...",
	'Why, permission to enter the haunted house, of course.',
	'Permission to search the haunted house is denied. End of discussion. Agent Lang, I want you to arrest that girl. And Miles, you should hurry on home now, my boy, before I really lose my temper.',
	'Wh-What is this...? Where are we...?',
	"Miles, my boy... What is the meaning of all this!? Do you plan to pay me back for all I've done for you with the conviction of my son!?",
	'Gnnnnnnrrrrrrrrr! You will regret this. I promise you that!',
	"See! That's justified self-defense! My boy was only trying to protect himself!",
	'W-Wait! I had nothing to do with the murder! The only person you should be arresting is Lance!',
	'Grrrrrrrr!',
	'And how could I possibly know the answer to such an asinine question!?',
	'You came to see... me?',
	'!',
	"Now, now, now, now, now! Please calm down. I honestly have no idea what you're talking about.",
	'..................',
	"Oh, Jacques! Thank goodness you're here...!",
	'Now, now... I say we let the courts resolve the rest.',
];

const AMANO_NOW_NOW_QUOTES = AMANO_QUOTES.filter((quote) => {
	const quoteLower = quote.toLowerCase();
	return quoteLower.includes('now, now') || quoteLower.includes('there, there');
});



export default {
	name: Events.MessageCreate,
	async execute(message) {},
};
