/* eslint-disable prefer-named-capture-group */

// Special thanks to https://github.com/mogade/badwords
export const SWEAR_PATTERNS = [
	/^[@a][$s]{2}$/,
	/[@a][$s]{2}h[0o][1l][3e][$s]?/,
	/b[@a][$s][+t][@a]rd /,
	/b[3e][@a][$s][+t][1i][@a]?[1l]([1i][+t]y)?/,
	/b[3e][@a][$s][+t][1i][1l][1i][+t]y/,
	/b[3e][$s][+t][1i][@a][1l]([1i][+t]y)?/,
	/b[1i][+t]ch[$s]?/,
	/b[1i][+t]ch[3e]r[$s]?/,
	/b[1i][+t]ch[3e][$s]/,
	/b[1i][+t]ch[1i]ng?/,
	/b[1l][0o]wj[0o]b[$s]?/,
	/c[1l][1i][+t]/,
	/^(c|k|ck|q)[0o](c|k|ck|q)[$s]?$/,
	/(c|k|ck|q)[0o](c|k|ck|q)[$s]u/,
	/(c|k|ck|q)[0o](c|k|ck|q)[$s]u(c|k|ck|q)[3e]d /,
	/(c|k|ck|q)[0o](c|k|ck|q)[$s]u(c|k|ck|q)[3e]r/,
	/(c|k|ck|q)[0o](c|k|ck|q)[$s]u(c|k|ck|q)[1i]ng/,
	/(c|k|ck|q)[0o](c|k|ck|q)[$s]u(c|k|ck|q)[$s]/,
	/^cum[$s]?$/,
	/cumm??[3e]r/,
	/cumm?[1i]ngcock/,
	/(c|k|ck|q)um[$s]h[0o][+t]/,
	/(c|k|ck|q)un[1i][1l][1i]ngu[$s]/,
	/(c|k|ck|q)un[1i][1l]{2}[1i]ngu[$s]/,
	/(c|k|ck|q)unn[1i][1l][1i]ngu[$s]/,
	/(c|k|ck|q)un[+t][$s]?/,
	/(c|k|ck|q)un[+t][1l][1i](c|k|ck|q)/,
	/(c|k|ck|q)un[+t][1l][1i](c|k|ck|q)[3e]r/,
	/(c|k|ck|q)un[+t][1l][1i](c|k|ck|q)[1i]ng/,
	/cyb[3e]r(ph|f)u(c|k|ck|q)/,
	/d[@a]mn/,
	/d[1i]ck/,
	/d[1i][1l]d[0o]/,
	/d[1i][1l]d[0o][$s]/,
	/d[1i]n(c|k|ck|q)/,
	/d[1i]n(c|k|ck|q)[$s]/,
	/[3e]j[@a]cu[1l]/,
	/(ph|f)[@a]g[$s]?/,
	/(ph|f)[@a]gg[1i]ng/,
	/(ph|f)[@a]gg?[0o][+t][$s]?/,
	/(ph|f)[@a]gg[$s]/,
	/(ph|f)[3e][1l]{1,2}[@a][+t][1i][0o]/,
	/(ph|f)u(c|k|ck|q)/,
	/(ph|f)u(c|k|ck|q)[$s]?/,
	/g[@a]ngb[@a]ng[$s]?/,
	/g[@a]ngb[@a]ng[3e]d/,
	/g[@a]y/,
	/h[0o]m?m[0o]/,
	/h[0o]rny/,
	/j[@a](c|k|ck|q)-?[0o](ph|f)(ph|f)?/,
	/j[3e]rk-?[0o](ph|f)(ph|f)?/,
	/j[1i][$sz]{1,2}m?/,
	/[ck][0o]ndum[$s]?/,
	/mast(e|ur)b(8|ait|ate)/,
	/n+[1i]+[gq]+[3e]*r+[$s]*/,
	/[0o]rg[@a][$s][1i]m[$s]?/,
	/[0o]rg[@a][$s]m[$s]?/,
	/p[3e]nn?[1i][$s]/,
	/p[1i][$s]{2}/,
	/p[1i][$s]{2}[0o](ph|f)(ph|f) /,
	/p[0o]rn/,
	/p[0o]rn[0o][$s]?/,
	/p[0o]rn[0o]gr[@a]phy/,
	/pr[1i]ck[$s]?/,
	/pu[$s]{2}[1i][3e][$s]/,
	/pu[$s]{2}y[$s]?/,
	/[$s][3e]x/,
	/[$s]h[1i][+t][$s]?/,
	/[$s][1l]u[+t][$s]?/,
	/[$s]mu[+t][$s]?/,
	/[$s]punk[$s]?/,
	/[+t]w[@a][+t][$s]?/,
];
