name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master # Use a pre-built SSH action
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            git config --global --add safe.directory /home/amano/discord
            cd /home/amano/discord
            mkdir temp-dir
            git clone https://github.com/grantchatterton/amano-discord-bot temp-dir
            mv temp-dir/.git /home/amano/discord
            rm -rf temp-dir
            git checkout .
            npm install --only=prod
            npm run deploy
            pm2 restart amano-discord-bot
