name: Docker CI/CD

on:
  push:
    branches: ["main"]
  paths:
    - 'src/**'

jobs:
  docker:
    name: Build and Deploy Container Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gchatterton/amano-discord-bot:latest
  deploy:
    name: Deploy the App to Production
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Restart/Redeploy the app on the VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            docker compose down --rmi all
            docker compose up -d --pull always
