name: "Deploy to Production Server"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build and Push Docker Image"
    types:
      - completed

jobs:
  deploy-production:
      name: Deploy to Production Server
      runs-on: ubuntu-latest
      steps:
        - name: Restart/redeploy the app on the VPS
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd ${{ secrets.VPS_PATH }}
              docker compose -f compose.yml -p amano-bot down --rmi all
              docker compose -f compose.yml -p amano-bot up -d --pull always
